// Vendoring detection: the half of the Zero Dependency rule the manifest
// cannot see.
//
// The bar here is asymmetric on purpose. Missing a vendored file is a gap;
// accusing a hand-written file of being copied is a false accusation, so the
// "does not fire" tests matter more than the "does fire" ones.

import { describe, test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { inspectFile, commentText, rank } from '../src/vendor.mjs';

async function withFile(name, body, fn) {
  const dir = await mkdtemp(join(tmpdir(), 'depx-vendor-'));
  try {
    const path = join(dir, name);
    await writeFile(path, body);
    return await fn(await inspectFile(path, name));
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
}

const ids = (report) => (report?.signals ?? []).map((s) => s.id).sort();

describe('comment extraction', () => {
  test('keeps comment text and drops code', () => {
    const text = commentText('const x = 1; // a note\nconst y = 2;\n');
    assert.match(text, /a note/);
    assert.doesNotMatch(text, /const/);
  });

  test('does not treat a comment marker inside a string as a comment', () => {
    const text = commentText('const url = "https://example.com/x";\n');
    assert.doesNotMatch(text, /example\.com/);
  });

  test('preserves line numbering', () => {
    const text = commentText('a\nb\n// third line\n');
    assert.equal(text.split('\n').length, 4);
    assert.equal(text.split('\n')[2].trim(), '// third line');
  });

  test('reads block comments', () => {
    const text = commentText('/* @license MIT */\nconst x = 1;\n');
    assert.match(text, /@license/);
  });
});

describe('signals that should fire', () => {
  test('a bundled file with a source map comment', async () => {
    await withFile('bundle.js', 'var x=1;\n//# sourceMappingURL=bundle.js.map\n', (r) => {
      assert.ok(ids(r).includes('source-map'));
    });
  });

  test('a minified file, on line length alone', async () => {
    await withFile('min.js', `var a=1;${'b=2;'.repeat(200)}\n`, (r) => {
      assert.ok(ids(r).includes('minified'));
    });
  });

  test('a copied file carrying a third-party licence header', async () => {
    const header = [
      '/*',
      ' * Some Library v4.17.21',
      ' * Copyright (c) 2016 Some Author',
      ' * Released under the MIT license',
      ' */',
      'function thing() { return 1; }',
    ].join('\n');
    await withFile('lib.js', header, (r) => {
      assert.ok(ids(r).includes('vendored-header'));
    });
  });

  test('a generated file that says so', async () => {
    await withFile('gen.go', '// Code generated by protoc. DO NOT EDIT.\npackage x\n', (r) => {
      assert.ok(ids(r).includes('generated'));
    });
  });

  test('a UMD wrapper', async () => {
    const umd =
      '(function (root, factory) {\n' +
      '  if (typeof exports === "object" && typeof define === "function") { factory(exports); }\n' +
      '})(this, function (e) {});\n';
    await withFile('umd.js', umd, (r) => {
      assert.ok(ids(r).includes('umd-wrapper'));
    });
  });
});

describe('signals that must not fire', () => {
  test('ordinary hand-written source is silent', async () => {
    const source = [
      '// Walks a directory and yields source files.',
      'export async function* walk(root) {',
      '  const ratio = width / height;',
      '  yield root;',
      '}',
    ].join('\n');
    await withFile('walk.mjs', source, (r) => assert.equal(r, null));
  });

  test("the author's own copyright line, with no licence body, is silent", async () => {
    await withFile('mine.js', '// Copyright 2026 Me\nconst x = 1;\n', (r) => {
      assert.equal(r, null);
    });
  });

  test('a file whose code mentions licence words is silent', async () => {
    // This is the shape of the detector itself: the marker words appear in
    // code, not in prose, and must not read as a licence header.
    const source = 'const MARKERS = [/@license\\b|@preserve\\b/, /DO NOT EDIT/i];\n';
    await withFile('detector.mjs', source, (r) => assert.equal(r, null));
  });

  test('a long data line under the threshold is silent', async () => {
    await withFile('data.js', `const t = "${'x'.repeat(400)}";\n`, (r) => {
      assert.equal(r, null);
    });
  });

  test('the detector does not flag its own source', async () => {
    const report = await inspectFile(
      new URL('../src/vendor.mjs', import.meta.url).pathname,
      'src/vendor.mjs',
    );
    assert.equal(report, null);
  });
});

describe('ranking', () => {
  test('puts the strongest evidence first', () => {
    const ordered = rank([
      { file: 'weak.js', signals: [{ id: 'generated' }] },
      { file: 'strong.js', signals: [{ id: 'source-map' }, { id: 'minified' }] },
    ]);
    assert.equal(ordered[0].file, 'strong.js');
  });
});

describe('minified detection needs more than one long line', () => {
  test('an inline SVG path does not read as minified', async () => {
    // Found against a real repo: a hand-written icon component whose <path d>
    // runs past 700 characters. One long line in an otherwise normal file is
    // not minification, and calling it that is a false accusation.
    const svg =
      'export function Icon() {\n' +
      '  return (\n' +
      `    <svg viewBox="0 0 24 24"><path d="${'M12 .5C5.37.5 0 5.78 0 12.29'.repeat(30)}" /></svg>\n` +
      '  );\n' +
      '}\n';
    await withFile('icon.tsx', svg, (r) => {
      assert.ok(!ids(r).includes('minified'), 'an SVG path is not minified output');
    });
  });

  test('several long class strings do not read as minified', async () => {
    // Also found against a real repo: shadcn/ui components carry a handful of
    // 600-character Tailwind class strings among many ordinary short lines,
    // averaging about 33 characters a line. It is the average that separates
    // this from a bundle, so the file has to be shaped like the real one.
    const long = `      className="${'focus:bg-accent data-[variant=destructive]:text-destructive '.repeat(9)}"`;
    const body = [];
    for (let i = 0; i < 4; i++) {
      body.push('function Item() {', '  return (', '    <div', long, '    />', '  );', '}', '');
      for (let j = 0; j < 20; j++) body.push('  // an ordinary line');
    }
    const source = body.join('\n') + '\n';
    const average = source.length / source.split('\n').length;
    assert.ok(average < 200, `fixture should look like real source, averaged ${average}`);
    await withFile('menu.tsx', source, (r) => {
      assert.ok(!ids(r).includes('minified'), 'long class strings are not minified output');
    });
  });

  test('a genuinely minified file is still caught', async () => {
    await withFile('bundle.js', `var a=1;${'b=2;'.repeat(200)}\nvar c=3;\n`, (r) => {
      assert.ok(ids(r).includes('minified'));
    });
  });
});
