// Vendoring detection.
//
// An empty manifest is trivially faked by pasting a library's source into
// src/. The Zero Dependency rules name this exactly - "a dependency with
// extra steps" - and score it against you, but nothing verifies it: the
// manifest still reads `{}` and every existing tool says the repo is clean.
//
// So we look at the code instead of the manifest, for the marks source
// leaves when it was not typed by the person shipping it. Every signal here
// is evidence, not proof, and the output says so: these are files a human
// should look at, not an accusation. A false accusation of cheating is worse
// than a missed one, so each signal is chosen to be rare in hand-written
// code and common in copied code.

import { readFile } from 'node:fs/promises';

/**
 * A single long line proves nothing: an inline SVG `<path d="...">`, a base64
 * data URI or a long regex all run past 500 characters in source a person
 * plainly wrote by hand, and a component file full of long Tailwind class
 * strings has several. What actually distinguishes minified output is that
 * *the whole file* lives on very few lines, so the average line length is the
 * discriminator and the long line alone is not.
 */
const MINIFIED_LINE = 500;
const MINIFIED_AVERAGE = 200;

/**
 * Bundler and generator leavings, in rough order of how damning they are.
 *
 * `where` says which view of the file a marker is matched against. A licence
 * header or a generated-file banner is by definition a comment, so matching
 * those against comment text only is both more precise and the reason this
 * module does not flag itself: the patterns below live in its code, not in
 * its prose.
 */
const MARKERS = [
  {
    id: 'source-map',
    where: 'comments',
    re: /[#@]\s*sourceMappingURL=/,
    why: 'carries a source map comment, which a build tool emits and a person does not write',
  },
  {
    id: 'license-pragma',
    where: 'comments',
    re: /@license\b|@preserve\b/,
    why: 'contains a bundler-preserved licence pragma, the mark of third-party code passed through a build',
  },
  {
    id: 'generated',
    where: 'comments',
    re: /\b(?:DO NOT EDIT|@generated|AUTO-?GENERATED|Code generated by)\b/i,
    why: 'declares itself generated, so it was not written by hand this weekend',
  },
  {
    id: 'umd-wrapper',
    where: 'code',
    re: /typeof\s+exports\s*===?\s*['"]object['"][\s\S]{0,120}?typeof\s+define\s*===?\s*['"]function['"]/,
    why: 'opens with a UMD wrapper, which is how a published package ships, not how source is written',
  },
  {
    id: 'vendored-header',
    where: 'comments',
    // A copyright line followed closely by a licence name: the header a
    // library carries. Matched together so a bare "Copyright <you>" line does
    // not trip it, and only in the head of the file.
    re: /Copyright\s*(?:\(c\)|©)?\s*\d{4}[\s\S]{0,200}?\b(?:MIT|Apache License|BSD|ISC|Mozilla Public|GNU General Public|LGPL)\b/i,
    why: 'carries a full third-party licence header, which is what copied library source looks like',
  },
];

/**
 * Pull out just the comment text, preserving line count so a reported line
 * number still points at the right place in the original file.
 *
 * Covers the two comment syntaxes that matter here - C-style `//` and
 * `/* *\/`, and hash-style `#` - which between them cover every language the
 * scanner supports. Comment markers inside string literals are skipped, so
 * a string containing "//" does not open a phantom comment.
 */
export function commentText(src) {
  const out = new Array(src.length).fill(' ');
  for (let i = 0; i < src.length; i++) {
    const c = src[i];
    if (c === '\n') { out[i] = '\n'; continue; }

    if (c === '"' || c === "'" || c === '`') {
      for (let j = i + 1; j < src.length; j++) {
        if (src[j] === '\\') { j++; continue; }
        if (src[j] === '\n' && c !== '`') { i = j - 1; break; }
        if (src[j] === c) { i = j; break; }
        if (j === src.length - 1) i = j;
      }
      continue;
    }

    const isLine = (c === '/' && src[i + 1] === '/') || c === '#';
    if (isLine) {
      const nl = src.indexOf('\n', i);
      const stop = nl === -1 ? src.length : nl;
      for (let k = i; k < stop; k++) out[k] = src[k];
      i = stop - 1;
      continue;
    }

    if (c === '/' && src[i + 1] === '*') {
      const end = src.indexOf('*/', i + 2);
      const stop = end === -1 ? src.length : end + 2;
      for (let k = i; k < stop; k++) out[k] = src[k] === '\n' ? '\n' : src[k];
      i = stop - 1;
      continue;
    }
  }
  return out.join('');
}

/**
 * Inspect one source file for signs it was copied rather than written.
 *
 * @param {string} path
 * @param {string} rel
 * @returns {Promise<{file: string, signals: Array<{id: string, why: string, line: number}>} | null>}
 */
export async function inspectFile(path, rel) {
  let source;
  try {
    source = await readFile(path, 'utf8');
  } catch {
    return null;
  }

  const signals = [];
  const lines = source.split('\n');
  const comments = commentText(source);

  // A licence header sits at the top of a file; a source map comment sits at
  // the bottom. Everything else is judged on the head, so a stray "@license"
  // deep inside a long file does not read as vendored code.
  const views = {
    comments: comments.split('\n').slice(0, 40).join('\n'),
    code: lines.slice(0, 40).join('\n'),
  };

  for (const marker of MARKERS) {
    const target = marker.id === 'source-map' ? comments : views[marker.where];
    const match = marker.re.exec(target);
    if (!match) continue;
    signals.push({
      id: marker.id,
      why: marker.why,
      line: target.slice(0, match.index).split('\n').length,
    });
  }

  const longest = lines.reduce((max, l, i) => (l.length > (lines[max]?.length ?? 0) ? i : max), 0);
  const average = source.length / Math.max(1, lines.length);
  if (lines[longest]?.length > MINIFIED_LINE && average > MINIFIED_AVERAGE) {
    signals.push({
      id: 'minified',
      why:
        `packs ${lines[longest].length} characters onto one line and averages ` +
        `${Math.round(average)} per line, which means minified or bundled output`,
      line: longest + 1,
    });
  }

  return signals.length ? { file: rel, signals } : null;
}

/**
 * Rank files by how strongly they look vendored, worst first, so the report
 * leads with the file a judge should open.
 */
export function rank(reports) {
  const weight = {
    'source-map': 5,
    minified: 5,
    'umd-wrapper': 4,
    'vendored-header': 3,
    'license-pragma': 2,
    generated: 1,
  };
  const score = (r) => r.signals.reduce((n, s) => n + (weight[s.id] ?? 1), 0);
  return [...reports].sort((a, b) => score(b) - score(a) || a.file.localeCompare(b.file));
}
